#!/bin/sh
# This script combines multiple abundance.tsv files generated by Kallisto into a single count matrix.


# Get list of abundance.tsv files (adjust path as needed)
FILES=$(find . -type f -name "abundance.tsv")

# Extract header (target_id) from the first file
awk 'NR>1 {print $1}' $(echo $FILES | awk '{print $1}') > target_ids.txt

header="target_id"

sed -i "1i $header" target_ids.txt

# For each abundance.tsv, extract est_counts column (tpm) and rename header to sample name
for f in $FILES; do
    sample=$(basename $(dirname "$f"))
    
    header=${sample%_transcripts_quant}

    awk -v s="$header" 'BEGIN{print s} NR>1{print $4}' "$f" > "${sample}_counts.txt"
done

# Paste all columns together: target_id + each sample's counts
paste target_ids.txt *_counts.txt > kallisto_count_matrix.tsv


# Clean up
rm target_ids.txt *_counts.txt

# combine sh not working properly

grep Cluster-10065.0.p1 kallisto_count_matrix.tsv

for f in $FILES; do

    grep Cluster-10065.0.p1 ${f}

done


for f in $FILES; do
    if ! diff -q <(awk 'NR>1 {print $1}' target_ids.txt) <(awk 'NR>1 {print $1}' "$f") > /dev/null; then
        echo "Error: Row mismatch detected in $f. Ensure all files have consistent rows."
        #exit 1
    fi
done
