title: "Step 1: Preprocessing RNA-seq libraries"
subtitle: "Quality metrics summarization"
intro_text: "The preprocessing step was perform using the all-in-one fastp preprocessing tool for FastQ files"
report_comment: "De novo transcriptome assembly for the specie Californiconus californicus"

show_analysis_paths: False
show_analysis_time: False

report_header_info:
  - Contact E-mail: "rgomez@cicese.edu.mx"
  - Application Type: "RNA-seq"
  - Project Type: "Transcriptome assembly"
  - Sequencing Platform: "NovaSeq 6000"
  - Sequencing Setup: "PE150"