set -e
true
true
/LUSTRE/apps/bioinformatica/SPAdes-3.15.5-Linux/bin/spades-core /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K21/configs/config.info /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K21/configs/mda_mode.info /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K21/configs/rna_mode.info
/LUSTRE/apps/bioinformatica/SPAdes-3.15.5-Linux/bin/spades-core /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K25/configs/config.info /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K25/configs/mda_mode.info /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K25/configs/rna_mode.info
/LUSTRE/apps/bioinformatica/SPAdes-3.15.5-Linux/bin/spades-core /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K49/configs/config.info /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K49/configs/mda_mode.info /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K49/configs/rna_mode.info
/LUSTRE/apps/bioinformatica/SPAdes-3.15.5-Linux/bin/spades-core /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/configs/config.info /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/configs/mda_mode.info /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/configs/rna_mode.info
/home/rgomez/bin/python /LUSTRE/apps/bioinformatica/SPAdes-3.15.5-Linux/share/spades/spades_pipeline/scripts/copy_files.py /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/before_rr.fasta /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/before_rr.fasta /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/assembly_graph_after_simplification.gfa /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/assembly_graph_after_simplification.gfa /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/transcripts.fasta /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/transcripts.fasta /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/transcripts.paths /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/transcripts.paths /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/assembly_graph_with_scaffolds.gfa /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/assembly_graph_with_scaffolds.gfa /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/assembly_graph.fastg /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/assembly_graph.fastg /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/hard_filtered_final_paths.fasta /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/hard_filtered_transcripts.fasta /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/K73/soft_filtered_final_paths.fasta /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/soft_filtered_transcripts.fasta
true
/home/rgomez/bin/python /LUSTRE/apps/bioinformatica/SPAdes-3.15.5-Linux/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/scaffolds.fasta --misc_dir /LUSTRE/bioinformatica_data/genomica_funcional/rgomez/californicus/07.Reference/01.Assembly/ONLY_Californiconus/Rnaspades_out/misc --threshold_for_breaking_scaffolds 3
true
